### ISSUE TITLE
关于训练时accuracy一直为0的问题

### ISSUE THREAD

**Issue by ZuoYuShen** [wujiyang/Face_Pytorch#14]
您好！我在用您的代码跑的时候，训练时的accuracy信息一直显示为0，而loss则有下降，请问是什么原因呢？我的pytorch版本是0.4.0，是因为版本的原因吗？

**Comment by qianchen94** [comment]
您好 我遇到了同样的问题 请问您是怎么解决的呢

**Comment by jilner** [comment]
您好 我遇到了同样的问题 请问您是怎么解决的呢
