### ISSUE TITLE
请问你有AgeDB原始图片吗？

### ISSUE THREAD

**Issue by olojuwin** [wujiyang/Face_Pytorch#15]
我用MTCNN裁剪成112X96,老是漏检

**Comment by wujiyang** [comment]
AgeDB的原始图片可以去AgeDB的官网下载，但是他们只是一堆文件，并没有进行配对，所以我直接采用InsightFace的AgeDB数据

**Comment by olojuwin** [comment]
非常感谢，InsightFace测试数据能否发个链接，我去看的时候没有能找到链接

**Comment by olojuwin** [comment]
> AgeDB的原始图片可以去AgeDB的官网下载，但是他们只是一堆文件，并没有进行配对，所以我直接采用InsightFace的AgeDB数据
非常感谢，请问你的转换工具在哪里？

**Comment by olojuwin** [comment]
> AgeDB的原始图片可以去AgeDB的官网下载，但是他们只是一堆文件，并没有进行配对，所以我直接采用InsightFace的AgeDB数据

AgeDB的原始图片可以去AgeDB的官网下载，但是他们只是一堆文件，并没有进行配对，所以我直接采用InsightFace的AgeDB数据
非常感谢，请问你的转换工具在哪里？

**Comment by wujiyang** [comment]
@olojuwin  ./utils/load_images_from_bin.py

**Comment by olojuwin** [comment]
> @olojuwin ./utils/load_images_from_bin.py

非常感谢，这么快就回复了，我刚刚找到··········

**Comment by olojuwin** [comment]
运行后，我得到了以下错误：
 in <module>
    logger = logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'getLogger'

**Comment by luluvi** [comment]
> 我用MTCNN裁剪成112X96,老是漏检

您好，我也想使用AgeDB的数据112X96的，遇到了跟您同样的问题，请问一下您是怎么解决的呢？可以分享一下嘛

**Comment by ZZH2950228** [comment]
AttributeError: 'module' object has no attribute 'getLogger'  我也遇到这个问题，请问您是怎么解决的呢？

**Comment by olojuwin** [comment]
> AttributeError: 'module' object has no attribute 'getLogger' 我也遇到这个问题，请问您是怎么解决的呢？

@ZZH2950228 安装日志模块
