### ISSUE TITLE
您好，请问是否能分享一下训练完的模型呢？

### ISSUE THREAD

**Issue by KovenYu** [wujiyang/Face_Pytorch#3]
有些时候我们需要直接利用训练好的模型进行一些测试，而并没有训练的硬件条件。请问能分享一下训练好的模型吗？特别是ResNet50的两个（在CASIA和MS1M上训练的）模型。谢谢！

**Comment by wujiyang** [comment]
实在不好意思哈，虽然我挺愿意分享的，但是实验室不允许~

**Comment by KovenYu** [comment]
@wujiyang 没事 我想办法自己训练好了。我对人脸这边不是很熟悉但是要加实验。。忘记说了我们也只用于科研用途（中山大学视觉ISEE实验室） 如果可以私下分享一下就好了~ 不行也没事儿啦 总之谢谢！

**Comment by ZCCDL** [comment]
> 实在不好意思哈，虽然我挺愿意分享的，但是实验室不允许~

你是有几块GPU跑的呢？谢谢

**Comment by wujiyang** [comment]
> > 实在不好意思哈，虽然我挺愿意分享的，但是实验室不允许~
> 
> 你是有几块GPU跑的呢？谢谢

TITAN XP 11GB * 4

**Comment by ruabuliuqiu** [comment]
> @wujiyang 没事 我想办法自己训练好了。我对人脸这边不是很熟悉但是要加实验。。忘记说了我们也只用于科研用途（中山大学视觉ISEE实验室） 如果可以私下分享一下就好了~ 不行也没事儿啦 总之谢谢！

ni de hua you dian yi si

**Comment by QuasarLight** [comment]
> > @wujiyang 没事 我想办法自己训练好了。我对人脸这边不是很熟悉但是要加实验。。忘记说了我们也只用于科研用途（中山大学视觉ISEE实验室） 如果可以私下分享一下就好了~ 不行也没事儿啦 总之谢谢！
> 
> ni de hua you dian yi si

I provide the pretrained models https://github.com/QuasarLight/Pytorch_Face_Recognition-

**Comment by ruabuliuqiu** [comment]
> > > @wujiyang 没事 我想办法自己训练好了。我对人脸这边不是很熟悉但是要加实验。。忘记说了我们也只用于科研用途（中山大学视觉ISEE实验室） 如果可以私下分享一下就好了~ 不行也没事儿啦 总之谢谢！
> > 
> > 
> > ni de hua you dian yi si
> 
> I provide the pretrained models https://github.com/QuasarLight/Pytorch_Face_Recognition-

thanks

**Comment by QuasarLight** [comment]
> > > > @wujiyang 没事 我想办法自己训练好了。我对人脸这边不是很熟悉但是要加实验。。忘记说了我们也只用于科研用途（中山大学视觉ISEE实验室） 如果可以私下分享一下就好了~ 不行也没事儿啦 总之谢谢！
> > > 
> > > 
> > > ni de hua you dian yi si
> > 
> > 
> > I provide the pretrained models https://github.com/QuasarLight/Pytorch_Face_Recognition-
> 
> thanks

This is my email ：1440896206@qq.com, we can communicate more[doge].
