### ISSUE TITLE
train.list的问题

### ISSUE THREAD

**Issue by tangyuanhenyuan** [wujiyang/Face_Pytorch#8]
您好，下载了您提供的数据集里面没有train.list文件，您可以提供吗？还是我们可以从哪里获取？刚刚做人脸还不太懂，如果问题太蠢还请多多包涵

**Comment by wujiyang** [comment]
train list就是文件名列表，自己生成一个就好了

**Comment by tangyuanhenyuan** [comment]
> train list就是文件名列表，自己生成一个就好了

我们自己有一个文件名+label的train list，但是放到您的代码里显示文件名和label无法分开[捂脸]再请教一下这是怎么回事？

**Comment by wujiyang** [comment]
你仔细看一下报错信息吧，可能是你的list格式问题：
0000045/013.jpg 0
0000045/014.jpg 0
0000045/015.jpg 0
0000099/001.jpg 1
0000099/002.jpg 1
0000099/003.jpg 1

**Comment by tangyuanhenyuan** [comment]
> 你仔细看一下报错信息吧，可能是你的list格式问题：
> 0000045/013.jpg 0
> 0000045/014.jpg 0
> 0000045/015.jpg 0
> 0000099/001.jpg 1
> 0000099/002.jpg 1
> 0000099/003.jpg 1

谢谢您~我们找到问题啦~

**Comment by tangyuanhenyuan** [comment]
您好！不好意思再打扰一下，对一个数据集如何生成trainlist文件呢？我看到deepinsight/insightface这个的预处理方法，只能把数据处理成mxnet读取的形式，并没有trainlist文件？

**Comment by wujiyang** [comment]
你自己的文件名加lable的list怎么生成的，按照一样的操作不就好了吗。
这只是一个简单的遍历文件名的工作。。。

**Comment by tangyuanhenyuan** [comment]
> 你自己的文件名加lable的list怎么生成的，按照一样的操作不就好了吗。
> 这只是一个简单的遍历文件名的工作。。。

遍历文件名没问题，可是label从哪里来……

**Comment by wujiyang** [comment]
lable 从0开始计数就行了，不用管对应的类别

**Comment by tangyuanhenyuan** [comment]
> lable 从0开始计数就行了，不用管对应的类别

非常感谢~
